### ISSUE TITLE
load_resource.ts:17 Uncaught (in promise)

### ISSUE THREAD

**Issue by zibous** [custom-cards/text-divider-row#7]
![Bildschirmfoto 2019-08-15 um 12 18 06](https://user-images.githubusercontent.com/30198737/63090597-16af6280-bf5c-11e9-8681-f5e74abfc77c.png)
**ERROR:
load_resource.ts:17 Uncaught (in promise) http://raspi.home:8123/community_plugin/text-divider-row/text-divider-row.js** 

**System-Info**
```ini
System Health
arch	armv7l
dev	false
docker	false
hassio	false
os_name	Linux
python_version	3.7.3
timezone	Europe/Vaduz
version	0.97.2
virtualenv	true
Lovelace
mode	yaml
resources	21
views	4
##
frontend:
  javascript_version: latest
```
**Browser: Safari, Chrome, Firefox.. on OSX** 

```yaml
## Installed version: 1.0.4
- url: /community_plugin/text-divider-row/text-divider-row.js
  type: module
````

```yaml
....
    unit: Watt
    type: "custom:mini-graph-card"
    upper_bound: 2000
    
  - type: "custom:text-divider-row"
    text: "test"

  - type: glance
    entities:
      - sensor.kostal_current_kw
      - sensor.psm_totalkw
      - sensor.psm_nettokw
title: "Ertrag vs. Verbrauch"
type: "custom:vertical-stack-in-card"
```
How can I fix the error ?
